AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

require:
  - rubocop/prompt

Prompt/InvalidFormat:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
