AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

plugins:
  - rubocop-prompt

Prompt/InvalidFormat:
  Enabled: true

Prompt/SystemInjection:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
