---
Prompt/InvalidFormat:
  Description: 'Ensure that system: blocks start with a Markdown heading.'
  Enabled: true
  VersionAdded: '0.1.0'

Prompt/CriticalFirstLast:
  Description: 'Ensure that labeled sections (### text) appear at the beginning or end, not in the middle.'
  Enabled: true
  VersionAdded: '0.1.0'

Prompt/SystemInjection:
  Description: 'Avoid dynamic interpolation in SYSTEM heredocs to prevent prompt injection vulnerabilities.'
  Enabled: true
  VersionAdded: '0.1.0'

Prompt/MaxTokens:
  Description: 'Ensure that documentation text in prompt-related code does not exceed the maximum token limit.'
  Enabled: true
  VersionAdded: '0.1.0'
  MaxTokens: 4000

Prompt/MissingStop:
  Description: 'Ensure that OpenAI::Client.chat calls include stop: or max_tokens: parameter.'
  Enabled: true
  VersionAdded: '0.1.0'

Prompt/TemperatureRange:
  Description: 'Ensure that high temperature values (> 0.7) are not used for precision tasks requiring accuracy.'
  Enabled: true
  VersionAdded: '0.1.0'
